MainApp/urls.py
from django.urls import path


from . import views


app_name= 'MainApp'

urlpatterns = [
    path('', views.index, name='index'), #name = always same name as view
    path("topics/", views.topics, name='topics'), #these are the pages for the website
    path('topics/<int:topic_id>/', views.topic, name='topic'), #ID = primary key
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'), #creating a new entry, needs to be under a topic to link the entry to
    path('edit_entry/<int:entry_id>/',views.edit_entry, name='edit_entry')
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')), #for homepage, include all URLs in the MainApp project?
    path('users/', include('users.urls')),
]

users/urls.py
#We import the path function and the include function so we can include some default 
#authentication URLs that Django has defined. 

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # registration page (below)
    path('register/', views.register, name='register')
]

MainApp/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:  #returns back result that you want returned
        return self.text #this gives the name of the topic
  
class Entry(models.Model): #associate Entry w/ many models??  #one topic can have multiple entries (1 to many relationship)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}" #returns first 50 characters of the entry in the text field
                            #whenever you call this method, everything it returns will be a string

users/models.py
from django.db import models

# Create your models here.

MainApp/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm): #this lets users enter texts from their side of the website 
    class Meta: #sub class since we want to save this information directly to the website
        model = Topic
        fields = ['text']
        labels = {'text':''}


class EntryForm(forms.ModelForm): #this lets users enter texts from their side of the website 
    class Meta: #sub class since we want to save this information directly to the website
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

MainApp/views.py
from django.shortcuts import render, redirect
from .forms import EntryForm, TopicForm
from MainApp.forms import TopicForm


from .models import Topic, Entry
# Create your views here.
#Homepage

def index(request):
    return render(request, 'MainApp/index.html') #must be consistent with naming on urls.py file
                                                    #render a page to the browser using the template
                                                    #folder inside templates folder must be same name as overarching folder


def topics(request):
    topics = Topic.objects.order_by('-date_added') #can't use topics.all, to make it descending order, add a mius sign in () #to get all topics: ".all()"

    context = {'topics': topics} #key = what you have to refer to it as in the HTML
                                 #value = what you called it in this file (on line 14)
    return render(request, 'MainApp/topics.html', context) #after the / is what the name of the file must be in the templates folder
                                        
def topic(request, topic_id): #loading individual topics onto the website (ex: chess and rock climbing)
    topic = Topic.objects.get(id= topic_id) #topic (singular) = topic in the overall topics page. Capital T Topic = object from models.py file 
    entries = topic.entry_set.all() #object

    context = {'topic' : topic, 'entries' :entries} #object, dictionary, passes information from the view to use in the template

    return render(request, 'MainApp/topic.html', context)

def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
            
        if form.is_valid(): #this validates if something on the form is specified as required and if it's on the form
            new_topic = form.save() #will directly save this to the database

            return redirect('MainApp:topics')

    context = {'form':form}
    return render(request, 'MainApp/new_topic.html', context)


def new_entry(request,topic_id): #need topic_id so it knows which topic to link the new entry to
                                #topic_id in () = 1,2,3... int object
    topic = Topic.objects.get(id=topic_id) #this is the topic OBJECT 
    #load entry based on post or get request
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)

        if form.is_valid():
            new_entry = form.save(commit=False) #form will only store: topic, text, & date added (automatic)
                                                #commit=False --> saves new entry object ready to write to DB, but doesn't actually save to DB yet
                                                #need to assign topic attribute before adding to DB
            new_entry.topic =  topic #line 47 is how we're getting the topic_id. assigning the topic to new_entry object
            new_entry.save()
            return redirect('MainApp:topic', topic_id=topic_id) #topic_id = defined in url file, 2nd topic_id = defined in line 47 (not the object, the int #?)

    context = {'form':form, 'topic':topic}
    return render(request, 'MainApp/new_entry.html', context)


def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic #how to get the associated topic on the entry we're editing. lower case b/c referring to the variable

    if request.method !='POST':
        form = EntryForm(instance=entry) #need the specific entry instance, not a new entry. instance = entry object in line 68.
    else:
        form = EntryForm(instance=entry, data=request.POST) #post request = saving. want to save it to same entry, so instance = entry
        if form.is_valid():
            form.save()
            return redirect('MainApp:topic', topic_id=topic.id) 

    context = {'form':form, 'topic':topic, 'entry':entry}
    return render(request, 'MainApp/edit_entry.html', context)

users/views.py
'''
-we want the register() view function to display a blank registration form when
registration page is 1st requested,

-process completed registration forms when they're submitted,

-if registration = successful, user should be automatically logged in
'''

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request): 
    """Register a new user"""
    if request.method != 'POST':
        #display blank registration form.
        form = UserCreationForm()
    else:
        form =UserCreationForm(data=request.POST) #saving information to the DB
            #username has appropriate characters, passwords match (w/username),
            #& user isn't trying to do anything malicious in their submission
        if form.is_valid():
        #the save() method returns the newly created user object,which we assign to new_user
            new_user = form.save()
            #log the user in and then redirect to the home page
            login(request, new_user)
            return redirect('MainApp:index')

    #display a blank or invalid form
    context = { 'form': form}
    return render(request,'registration/register.html', context)

MainApp/templates/mainapp/base.html
<p>
    <a href="{% url 'MainApp:index' %}">Learning Log</a>
    <a href="{% url 'MainApp:topics' %}">Topics</a>

    {% if user.is_authenticated %}
    Hello, {{ user.username }}
    <a href="{% url 'users:logout' %}">Log Out</a>
    {% else %}
    <a href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:login' %}">Log In</a>
    {% endif %}


</p>

{% block content %}
<!--text inside block = on site-->


{% endblock content %}

MainApp/templates/mainapp/edit_entry.html
{% extends "MainApp/base.html" %}


{% block content %}

<!--creating a link to navigate back to topic page-->

<p><a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit Entry:</p>


<form action="{% url 'MainApp:edit_entry' entry.id  %}" method='post'>
    <!--need to give int for topic_id. what are you passing through the view? topic_id = variable, topic.id = attribute ID of topic object-->

    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit">Save changes</button>

</form>

{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html" %}


{% block content %}
<p>Learning Log helps you keep track of your learning,
    for any topic you're learning about.
</p>

{% endblock content %}

MainApp/templates/mainapp/new_entry.html
{% extends "MainApp/base.html" %}


{% block content %}

<!--creating a link to navigate back to topic page-->

<p><a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>

<form action="{% url 'MainApp:new_entry' topic.id  %}" method='post'>
    <!--need to give int for topic_id. what are you passing through the view? topic_id = variable, topic.id = attribute ID of topic object-->

    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit">Add entry</button>

</form>

{% endblock content %}

MainApp/templates/mainapp/new_topic.html
{% extends "MainApp/base.html" %}


{% block content %}
<p>Add a new topic:</p>

<form action="{% url 'MainApp:new_topic' %}" method='post'>

    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit">Add topic</button>

</form>

{% endblock content %}

MainApp/templates/mainapp/topic.html
{% extends "MainApp/base.html" %}
<!-- 

the "topic" must be from the views file

this shows what's seen on each web page

e = object
-->

{% block content %}
<p>Topic: {{ topic }}</p>

<ul>
    <li>
        {% for e in entries %}
        <p>{{e.text }}</p>
        <p>{{e.date_added}}</p>
        <p><a href="{% url 'MainApp:edit_entry' e.id %}">Edit entry</a></p>
        <!--adding a link to edit the entries-->
    </li>
    {% empty %}
    <li> There are no entries for this topic yet.
    </li>
    {% endfor %}
</ul>

<p><a href="{% url 'MainApp:new_entry' topic.id %}">Add new entry</a></p>
<!--adding a new entry button after user has clicked into topic page-->

{% endblock content %}

MainApp/templates/mainapp/topics.html
{% extends "MainApp/base.html" %}


{% block content %}
<ul>
    {% for t in topics %}

    <li>
        <a href="{% url 'MainApp:topic' t.id%}">{{ t }}</a>
    </li>

    {% empty %}
    <li> No topics have been added yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'MainApp:new_topic' %}">Add a new topic</a>

{% endblock content %}